config1:
 NIND : 50
 MAXGEN : 100
 ELITIST : 0.05
 STOP_PERCENTAGE : 0.95
 PR_CROSS : 0.95
 PR_MUT : 0.05
 LOCALLOOP : 0
 CROSSOVER : tsp_xaltEdges

config2:
 NIND : 50
 MAXGEN : 100
 ELITIST : 0.05
 STOP_PERCENTAGE : 0.95
 PR_CROSS : 0.95
 PR_MUT : 0.05
 LOCALLOOP : 0
 CROSSOVER : tsp_xaltEdges
