config1:
 REPRESENTATION : REP_ADJACENCY
 NIND : 50
 MAXGEN : 100
 OFFSPRING_FACTOR : 3.0
 ELITE_PERCENTAGE : 0.0
 STOP_PERCENTAGE : 0.95
 PR_CROSS : 0.95
 PR_MUT : 0.05
 REINSERTION: tsp_genitor
 IMPROVE_POP: tsp_none
 CROSSOVER : tsp_xaltEdges
 MUTATION : tsp_inversion
 STOPCRITERIA : bestWorst
 SELECTION : tsp_sus

