config0:
 REPRESENTATION : REP_ADJACENCY
 NIND : 150
 PR_CROSS : 0.8
 PR_MUT : 0.3
 MAXGEN : 500
 ELITE_PERCENTAGE : 0.2
 OFFSPRING_FACTOR : 1.25
 STOP_PERCENTAGE : 0
 CROSSOVER : tsp_xaltEdges
 MUTATION : tsp_inversion
 SELECTION : tsp_sus
 REINSERTION: tsp_genitor
 IMPROVE_POP: tsp_none
 STOPCRITERIA: tsp_none
 RANKBASE: 0

config1:
 REPRESENTATION : REP_ADJACENCY
 NIND : 150
 PR_CROSS : 0.8
 PR_MUT : 0.3
 MAXGEN : 500
 ELITE_PERCENTAGE : 0.2
 OFFSPRING_FACTOR : 1.25
 STOP_PERCENTAGE : 0
 CROSSOVER : tsp_greedyHeuristicCrossover
 MUTATION : tsp_insertion
 SELECTION : tsp_deterministic_tournament
 REINSERTION: tsp_genitor
 IMPROVE_POP: tsp_none
 STOPCRITERIA: tsp_none
 RANKBASE: 0

config2:
 REPRESENTATION : REP_ADJACENCY
 NIND : 75
 PR_CROSS : 0.8
 PR_MUT : 0.3
 MAXGEN : 500
 ELITE_PERCENTAGE : 0.2
 OFFSPRING_FACTOR : 1.25
 STOP_PERCENTAGE : 0
 CROSSOVER : tsp_greedyHeuristicCrossover
 MUTATION : tsp_insertion
 SELECTION : tsp_deterministic_tournament
 REINSERTION: tsp_genitor
 IMPROVE_POP: tsp_localLoops
 STOPCRITERIA: tsp_none
 RANKBASE: 0

config3:
 REPRESENTATION : REP_ADJACENCY
 NIND : 75
 PR_CROSS : 0.8
 PR_MUT : 0.3
 MAXGEN : 500
 ELITE_PERCENTAGE : 0.2
 OFFSPRING_FACTOR : 1.25
 STOP_PERCENTAGE : 0
 CROSSOVER : tsp_greedyHeuristicCrossover
 MUTATION : tsp_insertion
 SELECTION : tsp_deterministic_tournament
 REINSERTION: tsp_genitor
 IMPROVE_POP: tsp_2opt
 STOPCRITERIA: tsp_none
 RANKBASE: 0