config1:
 REPRESENTATION : REP_ADJACENCY
 NIND : 50
 MAXGEN : 10
 OFFSPRING_FACTOR : 5
 ELITE_PERCENTAGE : 0.01
 STOP_PERCENTAGE : 0.95
 PR_CROSS : 0.75
 PR_MUT : 0.99
 REINSERTION: tsp_genitor
 IMPROVE_POP: tsp_none
 CROSSOVER : tsp_xaltEdges
 MUTATION : tsp_inversion
 STOPCRITERIA : dummy
 SELECTION : tsp_sus